import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
  title: "Rotinas - Dashboard",
  description: "Generated by create next app",
};

function page() {
  return (
    <div>Em breve...</div>
  )
}

export default page