import RoutineAnalytics from '@/components/routines/analytics/RoutineAnalytics';
import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
  title: "Rotinas - Dashboard",
  description: "Generated by create next app",
};

export default function RoutineAnalyticsPage() {
  return <RoutineAnalytics />
}