import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Plano de estudos - Dashboard",
  description: "Generated by create next app",
};

export default function TasksPage() {
  return <div>Em breve...</div>;
}
