import StudyPlanner from "@/components/estudos/StudyPlanner";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Plano de estudos - Dashboard",
  description: "Generated by create next app",
};

export default function StudyPlannerPage() {
  return <StudyPlanner />;
}
