import CardProfile from "@/components/CardProfile";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Perfil - Dashboard",
  description: "Generated by create next app",
};

export default function RoutinesPage() {
  return (
    <main className="container mx-auto p-4">
      <CardProfile />
    </main>
  )
}

