import TaskManager from "@/components/TaskManager"
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Tarefas - Dashboard",
  description: "Generated by create next app",
};

export default function TasksPage() {
  return (
    <main className="container mx-auto p-4">
      <TaskManager />
    </main>
  )
}