import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Routines - Dashboard",
  description: "Generated by create next app",
};

export default function RoutinesPage() {
  return (
    <main className="container mx-auto p-4">
      Page contente
    </main>
  )
}

