import RoutineManager from "@/components/routines/RoutineManager"
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Rotinas - Dashboard",
  description: "Generated by create next app",
};

export default function RoutinesPage() {
  return (
    <main className="container mx-auto p-4">
      <RoutineManager />
    </main>
  )
}

